// Сгенерировано tauri-specta из Rust (src-tauri). Не редактируйте вручную.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Диалог выбора папки библиотеки. `None` — пользователь отменил выбор. */
	chooseLibraryRoot: () => __TAURI_INVOKE<string | null>("choose_library_root"),
	/**  Кнопка «Добавить книги»: выбор файлов и импорт. `None` — диалог отменён. */
	pickAndImportBooks: () => __TAURI_INVOKE<string[] | null>("pick_and_import_books"),
	/**
	 *  «Сохранить как…»: путь выбирает человек в диалоге, интерфейс передаёт только содержимое.
	 *  Возвращает `false`, если диалог отменён.
	 */
	saveFileDialog: (suggestedName: string, filterName: string, extensions: string[], contentsBase64: string) => __TAURI_INVOKE<boolean>("save_file_dialog", { suggestedName, filterName, extensions, contentsBase64 }),
	metadataBackupsList: () => __TAURI_INVOKE<BackupInfo[]>("metadata_backups_list"),
	metadataBackupCreate: () => __TAURI_INVOKE<{
	id: string,
	createdAtMs: number,
	/**  Книг в метаданных копии (None — не удалось прочитать). */
	books: number | null,
	quotes: number | null,
} | null>("metadata_backup_create"),
	/**
	 *  Возвращает данные из копии. Перед этим сохраняет текущее состояние отдельной копией,
	 *  так что восстановление можно отменить. После вызова интерфейс нужно перезагрузить.
	 */
	metadataBackupRestore: (id: string) => __TAURI_INVOKE<null>("metadata_backup_restore", { id }),
	/**  Запускает обновление индекса в фоне; ход — событие `search-index-progress`. */
	searchReindex: () => __TAURI_INVOKE<boolean>("search_reindex"),
	searchStatus: () => __TAURI_INVOKE<SearchStatus>("search_status"),
	searchQuery: (query: string, limit: number | null) => __TAURI_INVOKE<SearchHit[]>("search_query", { query, limit }),
	opdsFetch: (url: string) => __TAURI_INVOKE<OpdsFeed>("opds_fetch", { url }),
	/**  Скачивает выбранные книги в корень библиотеки. Прогресс — событие `opds-import-progress`. */
	opdsImport: (items: OpdsImportItem[]) => __TAURI_INVOKE<OpdsImportResult>("opds_import", { items }),
	telegramStatus: () => __TAURI_INVOKE<TelegramStatus>("telegram_status"),
	/**  Пустой `api_hash` — взять сохранённый (форма не получает его обратно из бэкенда). */
	telegramSendCode: (apiId: number, apiHash: string, phone: string) => __TAURI_INVOKE<null>("telegram_send_code", { apiId, apiHash, phone }),
	telegramSignIn: (code: string, password: string | null) => __TAURI_INVOKE<TelegramSignInResult>("telegram_sign_in", { code, password }),
	/**
	 *  Возвращает `true`, если сеанс завершён и на сервере Telegram. `false` — локальные файлы
	 *  удалены, но сервер не подтвердил выход (нет сети): сеанс «Reader» стоит завершить вручную
	 *  в Telegram → Настройки → Устройства.
	 */
	telegramLogout: () => __TAURI_INVOKE<boolean>("telegram_logout"),
	telegramResolveChannel: (input: string) => __TAURI_INVOKE<TelegramChannelInfo>("telegram_resolve_channel", { input }),
	/**
	 *  Страница книг канала (от новых к старым). Ищем через `messages.search` с фильтром документов —
	 *  так не приходится листать всю ленту с картинками и текстом.
	 */
	sourceListFiles: (username: string, query: string | null, offsetId: number | null, limit: number | null) => __TAURI_INVOKE<RemoteFilesPage>("source_list_files", { username, query, offsetId, limit }),
	/**
	 *  Скачивает книги в корень библиотеки. Имя и тип берутся только из Telegram, не из webview.
	 *  Ошибка одного файла не прерывает остальные. Прогресс — событие `telegram-import-progress`.
	 */
	sourceImportFiles: (username: string, messageIds: number[]) => __TAURI_INVOKE<ImportResult>("source_import_files", { username, messageIds }),
	/**
	 *  Сколько книг появилось в канале после `since_ms` (до 100 — дальше не считаем).
	 *  Для значка «новое» у источника: один поисковый запрос на канал.
	 */
	sourceCountNew: (username: string, sinceMs: number) => __TAURI_INVOKE<number>("source_count_new", { username, sinceMs }),
};

/* Types */
export type BackupInfo = {
	id: string,
	createdAtMs: number,
	/**  Книг в метаданных копии (None — не удалось прочитать). */
	books: number | null,
	quotes: number | null,
};

export type ImportFailure = {
	messageId: number,
	name: string,
	error: string,
};

export type ImportProgress = {
	done: number,
	total: number,
	name: string,
};

export type ImportResult = {
	/**  Новые книги (пути относительно библиотеки). */
	added: string[],
	/**  Уже были в библиотеке — не скачивались. */
	existing: string[],
	failed: ImportFailure[],
};

export type IndexProgress = {
	done: number,
	total: number,
	current: string,
	finished: boolean,
	error: string | null,
};

export type OpdsAcquisition = {
	url: string,
	/**  `pdf`, `epub`, `fb2` или `fb2.zip`. */
	ext: string,
	size: number | null,
};

export type OpdsEntry = {
	id: string,
	title: string,
	authors: string[],
	summary: string | null,
	cover: string | null,
	/**  Ссылка на вложенный раздел каталога. */
	navigation: string | null,
	acquisitions: OpdsAcquisition[],
};

export type OpdsFeed = {
	url: string,
	title: string,
	entries: OpdsEntry[],
	next: string | null,
	/**  Шаблон поиска с `{searchTerms}`. */
	searchTemplate: string | null,
};

export type OpdsImportFailure = {
	title: string,
	error: string,
};

export type OpdsImportItem = {
	url: string,
};

export type OpdsImportResult = {
	added: string[],
	existing: string[],
	failed: OpdsImportFailure[],
};

export type OpdsProgress = {
	done: number,
	total: number,
	name: string,
};

export type RemoteBookFile = {
	id: string,
	name: string,
	size: number,
	ext: string,
	messageId: number,
	date: string | null,
	caption: string | null,
	/**  Файл с таким же именем и размером уже лежит в библиотеке. */
	inLibrary: boolean,
};

export type RemoteFilesPage = {
	files: RemoteBookFile[],
	/**  Передать в следующий запрос, чтобы получить более старые файлы; `None` — дальше пусто. */
	nextOffsetId: number | null,
};

export type SearchHit = {
	path: string,
	/**  `book` — текст книги, `note` — заметки, цитаты и выделения. */
	kind: string,
	title: string,
	label: string,
	/**  Фрагмент с `<b>` вокруг совпадений; остальной текст экранирован. */
	snippet: string,
};

export type SearchStatus = {
	indexedBooks: number,
	libraryBooks: number,
	running: boolean,
};

export type TelegramChannelInfo = {
	username: string,
	title: string,
};

export type TelegramSignInResult = {
	ok: boolean,
	needPassword: boolean | null,
	passwordHint: string | null,
	status: TelegramStatus | null,
};

export type TelegramStatus = {
	connected: boolean,
	phone: string | null,
	displayName: string | null,
	/**  Сохранённый API ID — чтобы форма входа не требовала вводить его заново. */
	apiId: number | null,
	/**  API Hash сохранён в бэкенде (сам hash в webview не отдаётся). */
	hasApiHash: boolean,
	/**  Ключ сессии в связке ключей ОС (`false` — в файле; `None` — неизвестно). */
	secureStorage: boolean | null,
};

